[workspace]

members = [
    "ck3-tiger",
    "vic3-tiger",
    "imperator-tiger",
    "utils",
    ".",
]

[package]
name = "tiger-lib"
version = "0.8.2"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Library used by the tools ck3-tiger, vic3-tiger, and imperator-tiger. This library holds the bulk of the code for them. It can be built either for ck3-tiger with the feature ck3, or for vic3-tiger with the feature vic3, or for imperator-tiger with the feature imperator, but not both at the same time."
homepage = "https://github.com/amtep/ck3-tiger"
repository = "https://github.com/amtep/ck3-tiger"
readme = "README.md"

[features]
default = ["ck3"]
ck3 = []
vic3 = []
imperator = []

[dependencies]
ansi_term = "0.12.1"
anyhow = "1"
as-any = "0.3.0"
bitflags = "2.3.3"
directories = "5.0.1"
encoding = "0.2"
fnv = "1"
home = "0.5"
image = "0.24"
lazy_static = "1"
once_cell = "1.18.0"
png = "0.17.6"
postcard = { version = "1.0.6", features = ["use-std"] }
rayon = "1.7.0"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
strum = "0.25"
strum_macros = "0.25"
thiserror = "1"
unicode-width = "0.1.9"
walkdir = "2"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.50"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "criterion"
harness = false

[profile.bench]
debug = true
